name: "Check & Cachix"

on:
  push:
    branches:
      - main
      - trying
      - staging

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://nrdxp.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - uses: cachix/cachix-action@v12
      with:
        name: nrdxp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Bash format check
      run: |
        nix -Lv develop -c -- fmt-bash --check

    # Check bud top level command
    - run: nix -Lv develop -c nix run .
    # TODO: possible testing strategies for ssh-show command
    # - uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.SSH_KEY }}
    #     known_hosts: |
    #     <remote host>: <ssh-ed25519>
    # - run: nix run --show-trace . -- ssh-show-ed25519 <remote host>
